
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BasicAPI.Models
{

using System;
    
internal partial class DBUser
{

    public int StudentID { get; set; }

    public string UserFirstName { get; set; }

    public string UserLastName { get; set; }

    public int UserID { get; set; }

    public int UserContactInfoID { get; set; }

    public string UserEmail { get; set; }

    public string UserPhone { get; set; }

}

}
