--USE APITest
--GO

/*
DROP TABLE atcDevAPI.UserContactInfo
DROP TABLE atcDevAPI.Users
DROP TABLE atcDevAPI.StudentContactInfo
DROP TABLE atcDevAPI.Students
*/

CREATE TABLE atcDevAPI.Students
(
	StudentID INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	StudentFirstName VARCHAR(50) NOT NULL,
	StudentLastName VARCHAR(50) NOT NULL,
)
GO

CREATE TABLE atcDevAPI.StudentContactInfo
(
	StudentContactInfoID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	StudentID INT NOT NULL,
	StudentPhone VARCHAR(25) NULL,
	StudentEmail VARCHAR(100) NOT NULL
)
GO

ALTER TABLE atcDevAPI.StudentContactInfo ADD FOREIGN KEY (StudentID) REFERENCES atcDevAPI.Students(StudentID);
GO

CREATE TABLE atcDevAPI.Users
(
	UserID INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	StudentID INT NOT NULL,
	UserFirstName VARCHAR(50) NOT NULL,
	UserLastName VARCHAR(50) NOT NULL
)
GO

ALTER TABLE atcDevAPI.Users ADD FOREIGN KEY (StudentID) REFERENCES atcDevAPI.Students(StudentID);
GO

CREATE TABLE atcDevAPI.UserContactInfo
(
	UserContactInfoID INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	UserID INT NOT NULL,
	UserPhone VARCHAR(25) NULL,
	UserEmail VARCHAR(100) NOT NULL	
)
GO

ALTER TABLE atcDevAPI.UserContactInfo ADD FOREIGN KEY (UserID) REFERENCES atcDevAPI.Users(UserID);
GO